version: '3'
services:
    web:
        build:
            context: ./web
        volumes:
            - ./www:/var/www
        ports:
            - "8000:80"
        depends_on:
            - app
    app:
        build:
            context: ./app
        volumes:
            - ./www:/var/www
        depends_on:
            - mysql
            # - redis
    mysql:
        image: mysql:latest
        # container_name: mysql_laravel_hello
        volumes:
            - mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: homestead
            MYSQL_USER: homestead
            MYSQL_PASSWORD: secret
        ports:
            - "3306:3306"
    adminer:
        image: adminer
        ports:
          - 10080:8080
        depends_on:
          - mysql
    # redis:
    #     restart: always
    #     image: redis:latest
    #     volumes:
    #         - ./redis:/data
    #     ports:
    #         - "6379:6379"
    #     command: redis-server --appendonly yes
volumes:
    mysql:
